config/routes.rb
Rails.application.routes.draw do  
  devise_for :users

  get 'users/tweets'
  resources :tweets
  resources :zombies
  get 'welcome/index'
  root to: 'welcome#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  validates :status, :text, presence: true
  
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tweets
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  
  validates_presence_of :name
  
  #has_many :tweets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
  
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index    
  end
  
  def show
    @zombie = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params(params))
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to :action =>'index', :notice => "Successfully created tweet."
    else
      render :action => 'new', :notice => "Something is wrong while creating tweet."
    end
  end
  
  private
  
  def tweet_params(params)
    params.require(:tweet).permit([:status, :text, :user_id])    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def tweets
    @user = User.find(params[:id])    
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  skip_before_filter :authenticate_user!
  layout :false
  
  def index
#    if user_signed_in?
#      redirect_to :tweets
#    end
  end
  
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  
  def show
    @zombie = Zombie.find(params[:id])
  end
  
  def index
    
  end

  def new
    @zombie = Zombie.new
  end

  def create
    @zombie = Zombie.create(name: params[:name], home: params[:home])
    if @zombie.save
      redirect_to :action => 'index'
    else
      redirect_to :action => 'new'
    end
  end
  
  def destroy    
    Zombie.find(params[:id]).destroy
    redirect_to :action => 'index'
    #Zombie.find(params[:id]).destroy
    #if @zombie
    #  @zombie.destroy
    #  redirect_to 'zombies'
    #else      
    #  redirect_to 'new'
    #end
    #redirect_to 'index'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zombie Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
</head>
  
<body>
		<!-- Navbar -->
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Twitter for Zombies</a>
            </div>
            <div>
              <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
              </p>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/tweets">Tweets</a></li>
                    <li class="active"><a href="/zombies">Zombies</a></li>
                </ul>
            </div>
        </div>
    </nav>  
    <div class='container'>
      <div class='jumbotron'>
        <!-- Alerts -->
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        
        <!-- YIELD -->
        <%= yield %>
      </div>
    </div>    

</body>
</html>

app/views/tweets/index.html.erb
<div align=center>
<h2>Tweets</h2>
</div>

<% tweets = Tweet.all %>
<% tweets.each do |tweet| %>  
  <h2><%= tweet.status %></h2>
  <p><%= tweet.text %></p>
  <p> Posted by <%= link_to User.find(tweet.user_id).email, controller: :users, action: :tweets, :id => tweet.user_id%> </p>
<% end %>

<% if tweets.size == 0 %>
  <p>There are no tweets yet.</p>
<% end %>

<%= button_to "Create new", new_tweet_path, :method=>:get, :class => 'btn btn-success'%>

app/views/tweets/new.html.erb
<table class="table table-light-bg table-condensed">
  <thead>
    <tr>
      <th>
        <h1>Tweets#new</h1>
        <p>Find me in app/views/tweets/new.html.erb</p>
      </th>
    </tr>
  </thead>



  <tbody>
    <tr>
      <td>
        <%= form_for @tweet, url: {action: "create"} do |f| %>
          <p/>    
          <%= @tweet.errors.full_messages_for(:status).first if @tweet.errors[:status].any? %>
          <%= f.label 'status' %>
          <%= f.text_field :status %>
          <br/>
          
          </p/>
          <%= @tweet.errors.full_messages_for(:text).first if @tweet.errors[:text].any? %>
          <%= f.label 'text' %>
          <%= f.text_field :text %>
          <br/>
          <p/>
          <p>
            <%= f.submit 'Save tweet', class: :'btn btn-success'%>
          </p>
          
        <% end %>
      </td>
    </tr>       
    
  </tbody>
</table>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<h1>Tweet</h1>

<tr>
  <td><h1><%= @tweet.name %></h1></td>
  <td><p><%= @tweet.home %></p></td> 
</tr>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/tweets.html.erb
<h2>All tweets for user <%= @user.email %> </h2>

<% Tweet.where(:user_id => @user.id).each do |tweet| %>
    Tweet</br>
    Status: <%= tweet.status %></br>
    Text: <%= tweet.text %></br>
    </br
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Grayscale - Free One Page Theme for Bootstrap 3</title>

    <!-- Bootstrap Core CSS -->
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Fonts -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Custom Theme CSS -->
    <%= stylesheet_link_tag params[:controller] %>
    <!--<link href="css/grayscale.css" rel="stylesheet">-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Zombie</span> Twitter
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#download">Download</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <section class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Grayscale</h1>
                        <p class="intro-text">A highly expensive, premium quality, extremely usable web application created by Vitalii Onufryk.</p>
                        <div class="page-scroll">
                            <a href="#about" class="btn btn-circle">
                                <i class="fa fa-angle-double-down animated"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Zombie Twitter</h2>
                <p>Zombie Twitter is a premium quality, non-free web application created by Vitalii Onufryk. It can be yours right now, all you need to do is sign-up and spen a lot of money. You can use this template for any purpose, personal or commercial.</p>
                <p>This striking, black and white theme features stock photographs by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Map skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                <p>With this template, just the slightest splash of color can make a huge impact on the overall presentation and design.</p>
            </div>
        </div>
    </section>

    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Grayscale</h2>
                    <p>You can download Grayscale for free on the download page at Start Bootstrap. You can also get the source code directly from GitHub if you prefer. Additionally, Grayscale is the first Start Bootstrap theme to come with a LESS file for easy color customization!</p>
                    <a href="http://startbootstrap.com/grayscale" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Zombie Twitter</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p>feedback@startbootstrap.com</p>
                <ul class="list-inline banner-social-buttons">
                    <li><a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li><a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li><a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    
    <div id='footer'>

    <!-- Core JavaScript Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <%= javascript_include_tag params[:controller] %>

</body>

</html>

app/views/zombies/index.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead><h2 class="text-center">Listing all Zombies</h2>
  <tr>	  
    <td class="bold">ID</td>
  	<td class="bold">Name</td>
  	<td class="bold">Home</td>
  	<td class="bold">Action</td>
  </tr>
  </thead>
  
  <tbody>
  <% Zombie.all.each do |zombie| %>
  <tr>
    <td><%= zombie.id %></td>
    <td><%= link_to zombie.name, zombie %></td>
  	<td><%= zombie.home %></td>  	
  	<td><%= button_to zombie, method: :delete, :confirm => "Are you sure?", :class => "btn btn-danger" do %>
  	      Delete
          <%= content_tag(:span, "", :class => "glyphicon glyphicon-trash") %>
  	    <% end %>
  	</td>    	
  </tr>   
  <% end %>
  
  
</tbody>
<tfoot>
  <tr><td colspan=0>
    <%= button_to "Create new", new_zombie_path, :method=>:get, :class => 'btn btn-success'%>    
  </td></tr>
</tfoot>
</table>

app/views/zombies/new.html.erb
<table>
	<tr><td><h1>New Zombie form</h1></td></tr>

	<%= form_for @zombie, url: {action: "create"} do |f| %>
		<tr>
			<td>Name <input type="text" name="name"></input></td>		
		</tr>
		<tr><td>Home <input type="text" name="home"></input></td></tr>
		<tr><td align=center><input type="submit" value="Create new Zombie"></td></tr>
  <%end%>

</table>

app/views/zombies/show.html.erb
<h1>Zombie</h1>

<tr>
	<td><h1><%= @zombie.name %></h1></td>
	<td><p><%= @zombie.home %></p></td>	
</tr>